In [ ]:
import tensorflow as tf

In [ ]:
tf.version

<module 'tensorflow._api.v2.version' from '/usr/local/lib/python3.7/dist-packages/tensorflow/_api/v2/version/__init__.py'>

In [ ]:
g=tf.constant('Hello World')

In [ ]:
print(g)

tf.Tensor(b'Hello World', shape=(), dtype=string)


In [ ]:
h=tf.constant('Hello World',shape=[6,2],name='i')

In [ ]:
print(h)

tf.Tensor(
[[b'Hello World' b'Hello World']
 [b'Hello World' b'Hello World']
 [b'Hello World' b'Hello World']
 [b'Hello World' b'Hello World']
 [b'Hello World' b'Hello World']
 [b'Hello World' b'Hello World']], shape=(6, 2), dtype=string)


In [ ]:
a=tf.constant(1.2,name='x',shape=[6,2])
print(a)

tf.Tensor(
[[1.2 1.2]
 [1.2 1.2]
 [1.2 1.2]
 [1.2 1.2]
 [1.2 1.2]
 [1.2 1.2]], shape=(6, 2), dtype=float32)


In [ ]:
b=tf.constant(2.4,name='y',shape=[6,2])
print(b)

tf.Tensor(
[[2.4 2.4]
 [2.4 2.4]
 [2.4 2.4]
 [2.4 2.4]
 [2.4 2.4]
 [2.4 2.4]], shape=(6, 2), dtype=float32)


In [ ]:
c=tf.add(a,b,name='Final')

In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist

In [ ]:
mnist = tf.keras.datasets.mnist

In [ ]:
(xtrain,ytrain) , (xtest,ytest) = mnist.load_data()

In [ ]:
xtrain , xtest = xtrain/255 , xtest/255

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
predictions=model(xtrain[:1]).numpy()
predictions

array([[-1.2560164e-03, -7.2826142e-04,  1.0781952e-03, -8.1715646e-04,
        -2.7584331e-03, -2.5141012e-04,  3.0853050e-03,  9.9122990e-06,
        -1.3245022e-03,  2.5570681e-03]], dtype=float32)

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09987837, 0.09993111, 0.10011178, 0.09992222, 0.09972844,
        0.09997876, 0.10031293, 0.1000049 , 0.09987153, 0.10025994]],
      dtype=float32)

In [ ]:
fn = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
fn(ytrain[:1],predictions).numpy()

2.3027973

In [ ]:
model.compile(optimizer='adam',
              loss=fn,
              metrics=['accuracy'])

In [ ]:
model.fit(xtrain,ytrain,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 1.2737 - accuracy: 0.6757
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.5788 - accuracy: 0.8397
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.4524 - accuracy: 0.8714
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3967 - accuracy: 0.8861
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3640 - accuracy: 0.8945


In [ ]:
model.evaluate(xtest,ytest,verbose=5)

[0.3039768934249878, 0.9154000282287598]

In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist

In [ ]:
(xtrain,ytrain),(xtest,ytest) = mnist.load_data()

In [ ]:
xtrain , xtest = xtrain/255 , xtest/255

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dropout(0.2)
])

In [ ]:
predictions=model(xtrain[:1]).numpy()

In [ ]:
predictions

array([[-0.24841376, -0.23849885,  0.03621191, -0.6148237 , -0.5506097 ,
         0.45972002, -0.15240765,  0.19766784, -0.27330127,  0.10777634]],
      dtype=float32)

In [ ]:
fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
fn(ytrain[:1],predictions).numpy()

1.7657189

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.0842596 , 0.08509918, 0.11200329, 0.05841032, 0.06228413,
        0.17106375, 0.09275009, 0.13162857, 0.08218848, 0.12031253]],
      dtype=float32)

In [ ]:
model.compile(optimizer='adam',
              loss=fn,
              metrics=['accuracy'])

In [ ]:
model.fit(xtrain,ytrain,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.4958 - accuracy: 0.8126
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.3378 - accuracy: 0.8552
Epoch 3/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2986 - accuracy: 0.8643
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2777 - accuracy: 0.8672
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.2583 - accuracy: 0.8750


In [ ]:
model.evaluate(xtest,ytest,verbose=5)

[0.07936038076877594, 0.9754999876022339]

In [ ]:
import tensorflow as tf

In [ ]:
mnist = tf.keras.datasets.mnist

In [ ]:
(xtrain,ytrain),(xtest,ytest) = mnist.load_data()

11501568/11490434 [==============================] - 0s 0us/step


In [ ]:
xtrain,xtest= xtrain/255 , xtest/255

In [ ]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape = (28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
prediction = model(xtrain[:1]).numpy()

In [ ]:
prediction

array([[-0.11720841, -0.2997589 ,  0.42752773,  0.02881434,  0.24720174,
         0.06376354, -0.02929918,  0.36845952, -0.17848626, -0.13654304]],
      dtype=float32)

In [ ]:
n = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
n(ytrain[:1],prediction).numpy()

2.303195

In [ ]:
tf.nn.softmax(prediction).numpy()

array([[0.083395  , 0.06947993, 0.14378577, 0.09650657, 0.12006082,
        0.09993903, 0.09105808, 0.13553858, 0.07843816, 0.08179808]],
      dtype=float32)

In [ ]:
model.compile(optimizer='adam',
              loss=n,
              metrics=['accuracy'])

In [ ]:
model.fit(xtrain,ytrain,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 6s 2ms/step - loss: 0.2947 - accuracy: 0.9148
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1442 - accuracy: 0.9572
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.1088 - accuracy: 0.9670
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0872 - accuracy: 0.9733
Epoch 5/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.0766 - accuracy: 0.9760


In [ ]:
model.evaluate(xtest,ytest,verbose=5)

[0.07418370991945267, 0.9778000116348267]

In [ ]:
import tensorflow as tf
mnist = tf.keras.datasets.mnist
(xtrain,ytrain),(xtest,ytest)=mnist.load_data()
xtrain , xtest = xtrain/255 , xtest/255 

In [ ]:
model = tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dense(10),
    tf.keras.layers.Dropout(0.2)
])

In [ ]:
predictions=model(xtrain[:1]).numpy()

In [ ]:
predictions

array([[-0.04882553,  0.2728452 ,  0.1856116 , -0.21216917, -0.9070099 ,
        -0.9856477 ,  0.5692123 , -0.49757484,  0.19513081,  0.4384752 ]],
      dtype=float32)

In [ ]:
n = tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
n(ytrain[:1],predictions).numpy()

3.3076866

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.09339995, 0.12883875, 0.11807594, 0.07932451, 0.03959514,
        0.03660075, 0.17328344, 0.05962897, 0.11920529, 0.15204729]],
      dtype=float32)

In [ ]:
model.compile(optimizer='adam',
              loss=n,
              metrics=['accuracy'])

In [ ]:
model.fit(xtrain,ytrain,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.5035 - accuracy: 0.8139
Epoch 2/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.3433 - accuracy: 0.8539
Epoch 3/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2996 - accuracy: 0.8629
Epoch 4/5
1875/1875 [==============================] - 4s 2ms/step - loss: 0.2767 - accuracy: 0.8690
Epoch 5/5
1875/1875 [==============================] - 6s 3ms/step - loss: 0.2611 - accuracy: 0.8711


In [ ]:
model.evaluate(xtest,ytest,verbose=5)

[0.07465793937444687, 0.9767000079154968]

In [ ]:
import matplotlib.pyplot as plt


In [ ]:
import matplotlib.image as npimg

In [ ]:
import tensorflow as tf


In [ ]:
from tensorflow.keras.models import Sequential

In [ ]:
import tensorflow.keras.backend as k

In [ ]:
import tensorflow.keras.layers as MaxPooling2D

In [ ]:
import tensorflow as tf

In [ ]:
mnist=tf.keras.datasets.mnist

In [ ]:
(xtrain,ytrain),(xtest,ytest) = mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
xtrain,xtest = xtrain/255,xtest/255

In [ ]:
model=tf.keras.models.Sequential([
    tf.keras.layers.Flatten(input_shape=(28,28)),
    tf.keras.layers.Dense(128,activation='relu'),
    tf.keras.layers.Dropout(0.2),
    tf.keras.layers.Dense(10)
])

In [ ]:
import numpy 

In [ ]:
predictions=model(xtrain[:1]).numpy()

In [ ]:
predictions

array([[ 0.42059827,  0.76974463,  0.02893002,  1.1675955 , -0.27863467,
         0.29293054, -0.5536439 ,  0.01643193,  0.5513075 ,  0.06048651]],
      dtype=float32)

In [ ]:
fn=tf.keras.losses.SparseCategoricalCrossentropy(from_logits=True)

In [ ]:
fn(ytrain[:1],predictions).numpy()

2.3751414

In [ ]:
tf.nn.softmax(predictions).numpy()

array([[0.10566584, 0.14981902, 0.07142253, 0.22302388, 0.05251237,
        0.09300134, 0.03988656, 0.07053544, 0.12042063, 0.07371232]],
      dtype=float32)

In [ ]:
model.compile(optimizer = 'adam',
               loss=fn,
               metrics='accuracy')

In [ ]:
model.fit(xtrain,ytrain,epochs=5)

Epoch 1/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.2973 - accuracy: 0.9141
Epoch 2/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1439 - accuracy: 0.9571
Epoch 3/5
1875/1875 [==============================] - 5s 2ms/step - loss: 0.1096 - accuracy: 0.9665
Epoch 4/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0885 - accuracy: 0.9725
Epoch 5/5
1875/1875 [==============================] - 5s 3ms/step - loss: 0.0779 - accuracy: 0.9760


In [ ]:
model.evaluate(xtest,ytest,verbose=5)

[0.0776669830083847, 0.9771000146865845]

In [ ]:
from tensorflow.keras.preprocessing.image import ImageDataGenerator

In [ ]:
import tensorflow.keras.backend as k

In [ ]:
import tensorflow as tf
import numpy as np

In [ ]:
tf.compat.v1.enable_eager_execution(
    config=None, device_policy=None, execution_mode=None
)

In [ ]:
(xtrain,ytrain),(_,_) = tf.keras.datasets.boston_housing.load_data(test_split=0)

In [ ]:
xtrain=xtrain.astype('float32')

In [ ]:
ytrain=ytrain.astype('float32')

In [ ]:
xtrain.shape

(506, 13)

In [ ]:
xtrain.dtype

dtype('int32')

In [ ]:
w=tf.zeros(shape=(13,1))
b=tf.zeros(shape=(1))

In [ ]:
def prediction(x,w,b):
  xw_matmul = tf.matmul(x,w)
  y=tf.add(xw_matmul,b)

  return y

In [ ]:
from numpy.lib.function_base import diff
def loss(y_actual,y_predicted):
  diff=y_actual-y_predicted
  sqr=tf.sqr(diff)
  avg=tf.reduce_mean(sqr)

  return avg

In [ ]:
def train(x,y_actual,w,b,learning_rate=0.01):
  with tf.GradientTape() as g:
    g.watch([w,b])
    current_prediction = prediction(x,w,b)
    current_loss = (y_actual,current_prediction)
    dw, db = g.gradient(current_loss[w,b])
    w = w - learning_rate*dw
    b = b-learning_rate*db

    return w,b

In [ ]:
#for i in range(100):
#w,b = train(xtrain, ytrain, w, b,learning_rate=0.01)
#print('Current Loss on Iteration', i,
#loss(ytrain,prediction(xtrain, w, b)).numpy())

In [ ]:
import sklearn.preprocessing

In [ ]:
from sklearn.preprocessing import Normalizer

In [ ]:
(xtrain,ytrain),(_,_) = tf.keras.datasets.boston_housing.load_data(test_split=0)

In [ ]:
xtrain=xtrain.astype('float32')

In [ ]:
ytrain=ytrain.astype('float32')

In [ ]:
xtrain.shape

(506, 13)

In [ ]:
ytrain.shape

(506,)

In [ ]:
transformer = Normalizer()

In [ ]:
xtrain=transformer.fit_transform(xtrain)

In [ ]:
xtrain[0]

array([0.0024119 , 0.        , 0.01592969, 0.        , 0.00105285,
       0.01201967, 0.17945357, 0.00778265, 0.00782785, 0.6007879 ,
       0.04109624, 0.7767189 , 0.03663436], dtype=float32)

In [ ]:
w=tf.zeros(shape=(13,1))
b=tf.zeros(shape=(1))

In [ ]:
def prediction(x,w,b):
  xw_matmul = tf.matmul(x,w)
  y=tf.add(xw_matmul,b)

  return y

In [ ]:
from numpy.lib.function_base import diff
def loss(y_actual,y_predicted):
  diff=y_actual-y_predicted
  sqr=tf.sqr(diff)
  avg=tf.reduce_mean(sqr)

  return avg

In [ ]:
def train(x,y_actual,w,b,learning_rate=0.01):
  with tf.GradientTape() as g:
    g.watch([w,b])
    current_prediction = prediction(x,w,b)
    current_loss = (y_actual,current_prediction)
    dw, db = g.gradient(current_loss[w,b])
    w = w - learning_rate*dw
    b = b-learning_rate*db

    return w,b

In [ ]:
#for i in range(100):
#w,b = train(xtrain, ytrain, w, b,learning_rate=0.01)
#print('Current Loss on Iteration', i,
#loss(ytrain,prediction(xtrain, w, b)).numpy())

In [ ]:
from sklearn.neighbors import KNeighborsRegressor

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
import tensorflow as tf

In [ ]:
(xtrain,ytrain),(_,_)=tf.keras.datasets.boston_housing.load_data(test_split=0)

In [ ]:
xtrain=xtrain.astype('float32')

In [ ]:
ytrain=ytrain.astype('float32')

In [ ]:
xtrain.dtype

dtype('float32')

In [ ]:
ytrain.dtype

dtype('float32')

In [ ]:
tf.compat.v1.enable_eager_execution(
    config=None, device_policy=None, execution_mode=None
)

In [ ]:
from sklearn.preprocessing import Normalizer

In [ ]:
transformer=Normalizer()

In [ ]:
xtrain=transformer.fit_transform(xtrain)

In [ ]:
model=tf.keras.models.Sequential()

In [ ]:
model.add=tf.keras.layers.Dense(1,input_shape=(13,))

In [ ]:
model.compile(optimizer='sgd',loss='mse')

In [ ]:
a=model.fit(xtrain,ytrain,epochs=100)

Epoch 1/100
16/16 [==============================] - 0s 2ms/step - loss: 586.6303
Epoch 2/100
16/16 [==============================] - 0s 3ms/step - loss: 586.6303
Epoch 3/100
16/16 [==============================] - 0s 2ms/step - loss: 586.6303
Epoch 4/100
16/16 [==============================] - 0s 2ms/step - loss: 586.6304
Epoch 5/100
16/16 [==============================] - 0s 4ms/step - loss: 586.6304
Epoch 6/100
16/16 [==============================] - 0s 3ms/step - loss: 586.6303
Epoch 7/100
16/16 [==============================] - 0s 3ms/step - loss: 586.6303
Epoch 8/100
16/16 [==============================] - 0s 3ms/step - loss: 586.6304
Epoch 9/100
16/16 [==============================] - 0s 2ms/step - loss: 586.6304
Epoch 10/100
16/16 [==============================] - 0s 3ms/step - loss: 586.6304
Epoch 11/100
16/16 [==============================] - 0s 3ms/step - loss: 586.6303
Epoch 12/100
16/16 [==============================] - 0s 3ms/step - loss: 586.6303
Epoch 13/100


In [ ]:
model.get_weights()

[]

In [ ]:
import tensorflow as tf

In [ ]:
tf.compat.v1.enable_eager_execution

<function tensorflow.python.framework.ops.enable_eager_execution(config=None, device_policy=None, execution_mode=None)>

In [ ]:
(xtrain,ytrain),(xtest,ytest) = tf.keras.datasets.mnist.load_data()

In [ ]:
xtrain.shape

(60000, 28, 28)

In [ ]:
xtrain[0]

array([[  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,
          0,   0],
       [  0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   0,   3,
         18,  18,  18, 126, 136, 175,  26, 166, 255, 247, 127,   0,   0,
          0,   0],
       [  

In [ ]:
xtest.shape

(10000, 28, 28)

In [ ]:
ytest.shape

(10000,)

In [ ]:
print(ytest[0:5])

[7 2 1 0 4]


In [ ]:
ytrain[0:2]

array([5, 0], dtype=uint8)

In [ ]:
ytrain=tf.keras.utils.to_categorical(ytrain,num_classes=10)

In [ ]:
ytest=tf.keras.utils.to_categorical(ytest,num_classes=10)

In [ ]:
ytrain.shape

(60000, 10)

In [ ]:
ytrain[0:9]

array([[0., 0., 0., 0., 0., 1., 0., 0., 0., 0.],
       [1., 0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 1., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0., 1.],
       [0., 0., 1., 0., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 1., 0., 0., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0., 0., 0., 0., 0., 0.]], dtype=float32)

In [ ]:
model=tf.keras.models.Sequential()

In [ ]:
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28)))

In [ ]:
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
model.add(tf.keras.layers.Dense(10,activation='Softmax'))

In [ ]:
model.compile(optimizer='sgd',loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.evaluate(xtest,ytest,verbose=32)

[0.6194717884063721, 0.9179999828338623]

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape (Reshape)           (None, 784)               0         
                                                                 
 batch_normalization (BatchN  (None, 784)              3136      
 ormalization)                                                   
                                                                 
 dense_2 (Dense)             (None, 10)                7850      
                                                                 
Total params: 10,986
Trainable params: 9,418
Non-trainable params: 1,568
_________________________________________________________________


In [ ]:
import tensorflow as tf

In [ ]:
(xtrain,ytrain),(xtest,ytest) = tf.keras.datasets.mnist.load_data()

11490434/11490434 [==============================] - 0s 0us/step


In [ ]:
xtrain.shape

(60000, 28, 28)

In [ ]:
ytrain.shape

(60000,)

In [ ]:
ytrain=tf.keras.utils.to_categorical(ytrain,num_classes=10)

In [ ]:
ytest=tf.keras.utils.to_categorical(ytest,num_classes=10)

In [ ]:
#Initialize Sequential model
model = tf.keras.models.Sequential()

#Reshape data from 2D to 1D -> 28x28 to 784
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28)))

#Normalize the data
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
#Add 1st hidden layer
model.add(tf.keras.layers.Dense(200, activation='relu'))

In [ ]:
#Add 2nd hidden layer
model.add(tf.keras.layers.Dense(100, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
#Add 3rd hidden layer
model.add(tf.keras.layers.Dense(60, activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
#Add 4th hidden layer
model.add(tf.keras.layers.Dense(30, activation='relu'))

In [ ]:
#Add OUTPUT layer
model.add(tf.keras.layers.Dense(10, activation='softmax'))


In [ ]:
sgd_optimizer = tf.keras.optimizers.SGD(lr=0.03, decay=0.001)
model.compile(optimizer=sgd_optimizer, loss='categorical_crossentropy', metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_1 (Reshape)         (None, 784)               0         
                                                                 
 batch_normalization_8 (Batc  (None, 784)              3136      
 hNormalization)                                                 
                                                                 
Total params: 3,136
Trainable params: 1,568
Non-trainable params: 1,568
_________________________________________________________________


In [ ]:
import matplotlib.pyplot as plt

In [ ]:
import matplotlib.image as npimg

In [ ]:
import tensorflow.keras.preprocessing.image as ImageDataGenerator

In [ ]:
import tensorflow.keras.preprocessing as image

In [ ]:
from tensorflow.keras.layers import Conv2D

In [ ]:
from tensorflow.keras.layers import MaxPool2D

In [ ]:
(xtrain,ytrain),(xtest,ytest) = tf.keras.datasets.mnist.load_data()

In [ ]:
ytrain =tf.keras.utils.to_categorical(ytrain,num_classes=10)

In [ ]:
ytest=tf.keras.utils.to_categorical(ytest,num_classes=10)

In [ ]:
model=tf.keras.models.Sequential()

In [ ]:
model.add(tf.keras.layers.Reshape((784,),input_shape=(28,28)))

In [ ]:
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
model.add(tf.keras.layers.Dense(100,activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
model.add(tf.keras.layers.Dense(30,activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
model.add(tf.keras.layers.Dense(60,activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
model.add(tf.keras.layers.Dense(200,activation='relu'))
model.add(tf.keras.layers.BatchNormalization())

In [ ]:
model.add(tf.keras.layers.Dense(200,activation='softmax'))

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_3 (Reshape)         (None, 784)               0         
                                                                 
 batch_normalization_9 (Batc  (None, 784)              3136      
 hNormalization)                                                 
                                                                 
 reshape_5 (Reshape)         (None, 784)               0         
                                                                 
 batch_normalization_10 (Bat  (None, 784)              3136      
 chNormalization)                                                
                                                                 
 dense_14 (Dense)            (None, 100)               78500     
                                                                 
 dense_15 (Dense)            (None, 100)              

In [ ]:
sgd_optimizer=tf.keras.optimizers.SGD(lr=0.01)

/usr/local/lib/python3.7/dist-packages/keras/optimizers/optimizer_v2/gradient_descent.py:108: UserWarning: The `lr` argument is deprecated, use `learning_rate` instead.
  super(SGD, self).__init__(name, **kwargs)


In [ ]:
model.compile(optimizer=sgd_optimizer,loss='categorical_crossentropy',metrics=['accuracy'])

In [ ]:
model.summary()

Model: "sequential_4"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 reshape_3 (Reshape)         (None, 784)               0         
                                                                 
 batch_normalization_9 (Batc  (None, 784)              3136      
 hNormalization)                                                 
                                                                 
 reshape_5 (Reshape)         (None, 784)               0         
                                                                 
 batch_normalization_10 (Bat  (None, 784)              3136      
 chNormalization)                                                
                                                                 
 dense_14 (Dense)            (None, 100)               78500     
                                                                 
 dense_15 (Dense)            (None, 100)              